
name: Krishna Kumar

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: " ğ•´tÃŸ ğ•·ÃªgÃ«Ã±dğ•­Ã¸t ğŸ‡®ğŸ‡³"

          replace: "TGXBOT"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Initial commit'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: LEGEND-OS

          commit_user_email: krishna045jaiswal@gmail.com
